name: vvd_ad
description: "vvd_ad_page"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/

  fonts:
    - family: Pretendard
      fonts:
        - asset: lib/assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/Pretendard-Black.ttf
          weight: 900