name: Deploy to S3 for vvd_ad_page

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Enable desktop
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter pub get

      - name: Build web application
        run: flutter build web --release

      - name: Copy routing files
        run: |
          cp web/404.html build/web/404.html
          # 각 경로에 대한 폴더 생성 및 index.html 복사 (중복 파일 제거)
          mkdir -p build/web/guide && cp web/guide.html build/web/guide/index.html
          mkdir -p build/web/prescription && cp web/prescription.html build/web/prescription/index.html
          mkdir -p build/web/price && cp web/price.html build/web/price/index.html
          mkdir -p build/web/a && cp web/a.html build/web/a/index.html
          mkdir -p build/web/b && cp web/a.html build/web/b/index.html
          mkdir -p build/web/efficacy && cp web/efficacy.html build/web/efficacy/index.html

      - name: Check AWS Identity
        run: aws sts get-caller-identity
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy to S3
        run: aws s3 sync build/web s3://${{ env.AWS_S3_BUCKET }} --delete
        env:
          AWS_S3_BUCKET: vvd-ad-page

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
